//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System.Runtime.Serialization;
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.ServiceModel.Channels;
    
    
    [GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContractAttribute(Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial struct Quote : IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalFieldAttribute()]
        private string CompanyField;
        
        [OptionalFieldAttribute()]
        private string IdField;
        
        [OptionalFieldAttribute()]
        private QuoteItem[] ItemsField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMemberAttribute()]
        public QuoteItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
    }
    
    [GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContractAttribute(Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial struct QuoteItem : IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalFieldAttribute()]
        private double PriceField;
        
        [OptionalFieldAttribute()]
        private int ProductIDField;
        
        [OptionalFieldAttribute()]
        private double QuantitiveInStockField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [DataMemberAttribute()]
        public double QuantitiveInStock
        {
            get
            {
                return this.QuantitiveInStockField;
            }
            set
            {
                this.QuantitiveInStockField = value;
            }
        }
    }
    
    [GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [ServiceContractAttribute(
        ConfigurationName="MarvellousWorks.PracticalPattern.WebServiceDIP.Client.QuoteService.IQuote")]
    public interface IQuote
    {
        
        [OperationContractAttribute(Action="http://tempuri.org/IQuote/GetQuote", 
            ReplyAction="http://tempuri.org/IQuote/GetQuoteResponse")]
        Quote GetQuote(string id);
    }

//[ServiceContract]
//public interface IAdvancedQuote
//{

//    [OperationContractAttribute(Action = "http://tempuri.org/IQuote/GetQuote",
//        ReplyAction = "http://tempuri.org/IQuote/GetQuoteResponse")]
//    Quote GetQuote(string id);

//    [OperationContractAttribute(Action = "http://tempuri.org/IAdvancedQuote/GetCompanyQuotes",
//    ReplyAction = "http://tempuri.org/IAdvancedQuote/GetCompanyQuotesResponse")]
//    Quote[] GetCompanyQuotes(string company);
//}
    
    [GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IQuoteChannel : IQuote, IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class QuoteClient : ClientBase<IQuote>, IQuote
    {
        
        public QuoteClient()
        {
        }
        
        public QuoteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public QuoteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public QuoteClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public QuoteClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Quote GetQuote(string id)
        {
            return base.Channel.GetQuote(id);
        }
    }
}
