//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.IContact")]
    public interface IContact
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContact/CreateDTO", ReplyAction="http://tempuri.org/IContact/CreateDTOResponse")]
        MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.Contact CreateDTO(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContact/SaveDTO", ReplyAction="http://tempuri.org/IContact/SaveDTOResponse")]
        void SaveDTO(MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.Contact dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IContactChannel : MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.IContact, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ContactClient : System.ServiceModel.ClientBase<MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.IContact>, MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.IContact
    {
        
        public ContactClient()
        {
        }
        
        public ContactClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ContactClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ContactClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ContactClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.Contact CreateDTO(int id)
        {
            return base.Channel.CreateDTO(id);
        }
        
        public void SaveDTO(MarvellousWorks.PracticalPattern.WebServiceDTO.Client.ContactService.Contact dto)
        {
            base.Channel.SaveDTO(dto);
        }
    }
}
